## Numpy start

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr=np.arange(10)

print(arr)
print(arr.reshape(2,5))
print(arr*5)

arr2=np.array([[1,2,3],[4,5,6]])
print("\n",arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 0  5 10 15 20 25 30 35 40 45]

 [[1 2 3]
 [4 5 6]]


In [21]:
zeroes=np.zeros((2,3))
ones=np.ones((3,2))
full=np.full((5,2),9)

print(zeroes)
print(ones)
print(full)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[9 9]
 [9 9]
 [9 9]
 [9 9]
 [9 9]]


## Array Properties

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


reshape, ravel, flatten, transpose

In [ ]:
arr=arr.reshape(3,2) # reassinging a reshaped copy to og
print(arr)
print(arr.flatten()) #returns copy
print(arr.ravel()) #returns view of og
print(arr.T) #transpose

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]
