## Selection

In [8]:
import numpy as np

In [ ]:
list=[[1,2,3],[4,5,6]]
print(list[1][1])

arr=np.arange(1,7).reshape(2,3)
print(arr[1,1]) #acessing supports [1,1] as well

print(arr[1]) #full row
print(arr[:,1]) # full col

5
5
[4 5 6]
[2 5]


## Sorting

In [ ]:
arr=np.array([4,1,6,7,2,9,10])
print(np.sort(arr),"\n")

arr_2d=np.array([[3,1],[2,5],[6,4]])
print(np.sort(arr_2d,axis=0),"\n") #axis=0 (makes each colsorted)
print(np.sort(arr_2d,axis=1)) #axis=1 (makes reach row sorted)
# print(np.sort(arr_2d,axis=2)) # error

[ 1  2  4  6  7  9 10] 

[[2 1]
 [3 4]
 [6 5]] 

[[1 3]
 [2 5]
 [4 6]]


## Filter + filter with mask

In [42]:
arr=np.arange(1,11)
print(arr)
print(arr[arr%2==0],"\n")

mask=arr>5 # making a mask
print(mask)
print(arr[mask],"\n")


[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10] 

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10] 



# np.where() + access with indices

In [ ]:
indices=[1,3,5]
print(arr[indices])

where_res=np.where(arr>5) #returns indices of the "arr" where val>5
print(where_res)
print(arr[where_res]) 

[2 4 6]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


make conditions arrays form np.where

In [48]:
condition_array=np.where(arr>5,arr*5,arr) # makes an array where when val>5 in array it does it *4, else keeps it the same
print(condition_array)

[ 1  2  3  4  5 30 35 40 45 50]


# Add data

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b) #elem wise is def in numpy
print(np.concat((a,b)),"\n") # concats np arrays, same as python list +

arr=np.array([[1,2,3],[4,5,6]])
new_row=np.array([7,8,9])

arr_with_nrow=np.vstack((arr,new_row)) # adds new row 
print(arr_with_nrow,"\n") 

new_col=np.array([[9],[0]])
arr_with_ncol=np.hstack((arr,new_col)) # adds new col
print(arr_with_ncol)



[5 7 9]
[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3 9]
 [4 5 6 0]]


# Array compatibilty

In [58]:
arr1=np.array([1,2,3])
arr2=np.array([1,2])
print(arr1.shape==arr2.shape)

False


# Delete data

In [ ]:
arr=np.arange(7)
arr_after_del=np.delete(arr,3) #removes index=3 val
print(arr_after_del)

[0 1 2 4 5 6]
